export const emptyType ={
    car:{
        mode:'car',
        icon:"http://cdn.uviewui.com/uview/empty/car.png"
    },
    page:{
        mode:'page',
        icon:"http://cdn.uviewui.com/uview/empty/page.png"
    },
    search:{
        mode:'search',
        icon:"http://cdn.uviewui.com/uview/empty/search.png"
    },
    address:{
        mode:'address',
        icon:"http://cdn.uviewui.com/uview/empty/address.png"
    },
    wifi:{
        mode:'wifi',
        icon:"http://cdn.uviewui.com/uview/empty/wifi.png"
    },
    order:{
        mode:'order',
        icon:"http://cdn.uviewui.com/uview/empty/wifi.png"
    },
    coupon:{
        mode:'coupon',
        icon:"http://cdn.uviewui.com/uview/empty/wifi.png"
    },
    favor:{
        mode:'favor',
        icon:"http://cdn.uviewui.com/uview/empty/favor.png"
    },
    permission:{
        mode:'permission',
        icon:"http://cdn.uviewui.com/uview/empty/permission.png"
    },
    history:{
        mode:'history',
        icon:"http://cdn.uviewui.com/uview/empty/history.png"
    },
    news:{
        mode:'news',
        icon:"http://cdn.uviewui.com/uview/empty/news.png"
    },
    message:{
        mode:'message',
        icon:"http://cdn.uviewui.com/uview/empty/message.png"
    },
    list:{
        mode:'list',
        icon:"http://cdn.uviewui.com/uview/empty/list.png"
    },
    data:{
        mode:'data',
        icon:"http://cdn.uviewui.com/uview/empty/data.png"
    },

};